package org.springframework.social.xing.api;

/**
 *
 */
public enum FormOfEmployment {
    FULL_TIME_EMPLOYEE, PART_TIME_EMPLOYEE, INTERN, FREELANCER, OWNER, PARTNER, BOARD_MEMBER, VOLUNTEER SELF_EMPLOYED, SHAREHOLDER, CIVIL_SERVANT, RECRUITER;
}
